### ISSUE TITLE
wysiwyg a little different than the normal one

### ISSUE THREAD

**Issue by bansay** [tacowordpress/addmany#3]
Howdy!! 

Noticing the WYSIWYG for AddMany is a little different than the normal WYSIWYG, are there any limitations to using the latest WYSIWYG in WordPress for AddMany?

The issue is I was hoping to be able to create inline links, unordered/ordered lists, and possibly, be able to use the AddMedia functionality in the WYSIWYG for AddMany.

Let me know your thoughts! No big deal though, at least for now :)

Thank you!

**Comment by jasand-pereza** [comment]
That's been an issue since AddMany was built. I haven't invested much time
in figuring it out but I can see how it would be important. I'll try to
look into it sometime this week.

**Comment by jasand-pereza** [comment]
Closing for now. As a note for future reference, changing the post_content WYSIWYG to text mode and saving the post causes AddMany WYSIWYGs to behave differently. To revert back, just switch back to reg mode and save again.
